name: Install and check
description: Install MDAnalysis and check it's installed
inputs:
  install-version:
    description: Input version to install
    required: true
    default: latest
  include-tests:
    description: Whether to install MDAnalysisTests
    required: true
    default: false
  installer:
    description: pip, conda, or mamba
    required: true
    default: pip
  shell:
    description: shell to use
    required: true
    default: bash
outputs:
  installed-version:
    description: Installed MDAnalysis version
    value: "${{ steps.print-version.outputs.installed-version }}"


runs:
  using: "composite"
  steps:
    - name: run
      uses: ./
      with:
        version: ${{ inputs.install-version }}
        install-tests: ${{ inputs.include-tests }}
        installer: ${{ inputs.installer }}
        shell: ${{ inputs.shell }}
    
    - name: Check version
      shell: python
      run:
        import MDAnalysis
        assert MDAnalysis.__version__ == ${{ inputs.expected-version }}
    
    - name: Check MDAnalysisTests
      if: ${{ matrix.include-tests }}
      shell: python
      run:
        from MDAnalysis.tests.datafiles import PDB
