name: CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  schedule:
    # Weekly tests at midnight on Sundays run on main by default:
    #   Scheduled workflows run on the latest commit on the default or base branch.
    #   (from https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule)
    - cron: "0 0 * * 0"


concurrency:
  # Specific group naming so CI is only cancelled
  # within same PR or on merge to main
  group: "${{ github.ref }}-${{ github.head_ref }}-${{ github.workflow }}"
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}

env:
  MDANALYSIS_DEVELOP_VERSION: "2.8.0-dev0"
  MDANALYSIS_LATEST_RELEASE: "2.7.0"
  MDANALYSIS_PREVIOUS_RELEASE: "2.6.1"

jobs:
  gen-python-matrix:
    runs-on: ubuntu-latest
    outputs:
      python-matrix: ${{ steps.get-compatible-python.outputs.python-versions }}
      latest-python: ${{ steps.get-compatible-python.outputs.latest-python }}
      oldest-python: ${{ steps.get-compatible-python.outputs.oldest-python }}
      stable-python: ${{ steps.get-compatible-python.outputs.stable-python }}
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - id: get-compatible-python
        uses: MDAnalysis/mdanalysis-compatible-python@main

  main-tests:
    runs-on: ${{ matrix.os }}
    needs: gen-python-matrix
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ${{ fromJSON(needs.gen-python-matrix.outputs.python-matrix) }}
        installer: ["pip", "micromamba"]
        include-tests: [true, false]
        mdanalysis-version: ["develop", "latest", "previous"]

        exclude:
          - python-version: "${{ needs.gen-python-matrix.outputs.latest-python }}"
            mdanalysis-version: "previous"

          - python-version: "${{ needs.gen-python-matrix.outputs.oldest-python }}"
            mdanalysis-version: "develop"

        include:
          - os: windows-latest
            python-version: "${{ needs.gen-python-matrix.outputs.stable-python }}"
            installer: conda
            include-tests: true
            mdanalysis-version: "latest"

          - os: macOS-latest
            python-version: "${{ needs.gen-python-matrix.outputs.stable-python }}"
            installer: conda
            include-tests: false
            mdanalysis-version: "latest"

    steps:
    - uses: actions/checkout@v3

    - id: environment-setup
      run: |
        if [[ ${{ matrix.installer }} == 'pip' ]] ; then
          USE_SHELL="bash"
        else
          USE_SHELL="bash -l {0}"
        fi

        echo "action-shell=${USE_SHELL}" >> $GITHUB_OUTPUT

        if [[ ${{ matrix.mdanalysis-version }} == 'previous' ]] ; then
          INSTALL_VERSION=${MDANALYSIS_PREVIOUS_RELEASE}
        else
          INSTALL_VERSION=${{ matrix.mdanalysis-version }}
        fi

        echo "action-install-version=${INSTALL_VERSION}" >> $GITHUB_OUTPUT

    - name: Install mamba Python ${{ matrix.python-version }}
      if: ${{ matrix.installer == 'micromamba' }}
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: False
        environment-name: mda
        extra-specs: |
          python==${{ matrix.python-version }}
          pip
        channels: conda-forge

    - name: Install conda Python ${{ matrix.python-version }}
      if: ${{ matrix.installer == 'conda' }}
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        add-pip-as-python-dependency: true
        architecture: x64
        mamba-version: "*"
        channels: conda-forge, defaults
        auto-update-conda: true
        show-channel-urls: true

    - name: Setup Python ${{ matrix.python-version }}
      if: ${{ matrix.installer == 'pip' }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - id: Install
      uses: ./
      with:
        version: ${{ steps.environment-setup.outputs.action-install-version }}
        install-tests: ${{ matrix.include-tests }}
        installer: ${{ matrix.installer }}
        shell: ${{ steps.environment-setup.outputs.action-shell }}

    - name: Check version
      run: |
        case "${{ matrix.mdanalysis-version }}"  in 
          "develop") VERSION="'${MDANALYSIS_DEVELOP_VERSION}'" ;;
          "latest") VERSION="'${MDANALYSIS_LATEST_RELEASE}'";;
          "previous") VERSION="'${MDANALYSIS_PREVIOUS_RELEASE}'" ;;
          *) VERSION="'${{ matrix.mdanalysis-version }}'" ;;
        esac

        echo "Expecting version $VERSION for installed version ${{ steps.environment-setup.outputs.action-install-version }} "

        python -c "import MDAnalysis; assert MDAnalysis.__version__ == ${VERSION}, f'incorrect version {MDAnalysis.__version__}'"

        if [[ "${{ matrix.include-tests }}" == "true" ]] ; then
          python -c "import MDAnalysisTests; assert MDAnalysisTests.__version__ == ${VERSION}, f'incorrect test version {MDAnalysis.__version__}'"

        else
          if [[ $(python -m pip list | grep "^MDAnalysisTests ") ]] ; then
            echo "MDAnalysisTests is installed even though it shouldn't be!"
            exit 1
          fi
        fi

  test-on-preinstalled-conda:
    needs: gen-python-matrix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install mamba Python ${{ needs.gen-python-matrix.outputs.stable-python }}
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: ./.github/test-environment.yaml
          environment-name: mda
          extra-specs: |
            python==${{ needs.gen-python-matrix.outputs.stable-python }}
            pip
          channels: conda-forge

      - name: Install
        uses: ./
        with:
          version: ${{ env.MDANALYSIS_PREVIOUS_RELEASE }}
          install-tests: false
          installer: micromamba
          shell: bash -l {0}
        
      - name: Check version
        run: |
          python -c "import MDAnalysis; assert MDAnalysis.__version__ == '${{ env.MDANALYSIS_PREVIOUS_RELEASE }}'"
          if [[ $(python -m pip list | grep "^MDAnalysisTests ") ]] ; then
            echo "MDAnalysisTests is installed even though it shouldn't be!"
            exit 1
          fi

  test-on-preinstalled-pip:
    needs: gen-python-matrix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python ${{ needs.gen-python-matrix.outputs.stable-python }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ needs.gen-python-matrix.outputs.stable-python }}

      - name: Install MDAnalysis
        shell: bash
        run: |
          # fun with versions
          python -m pip install MDAnalysis==${{ env.MDANALYSIS_PREVIOUS_RELEASE }} MDAnalysisTests==${{ env.MDANALYSIS_PREVIOUS_RELEASE }}
          python -m pip install MDAnalysis==${{ env.MDANALYSIS_LATEST_RELEASE }} MDAnalysisTests==${{ env.MDANALYSIS_LATEST_RELEASE }}
          python -m pip install MDAnalysis==${{ env.MDANALYSIS_PREVIOUS_RELEASE }} MDAnalysisTests==${{ env.MDANALYSIS_PREVIOUS_RELEASE }}

      - name: Install
        uses: ./
        with:
          version: develop
          install-tests: true
          installer: pip
          shell: bash
        
      - name: Check version
        run: |
          python -c "import MDAnalysis; assert MDAnalysis.__version__ == '${{ env.MDANALYSIS_DEVELOP_VERSION }}'"
          python -c "import MDAnalysisTests; assert MDAnalysisTests.__version__ == '${{ env.MDANALYSIS_DEVELOP_VERSION }}'"
